const RESPONSE_STATUS = {
    EXISTING_SERIALS: "EXISTING SERIALS",
    SERVER_ERROR: "SERVER ERROR",
    NO_PN_STOCK: "NO PN STOCK",
    SERIAL_NOT_FOUND: "SERIAL NOT FOUND",
    ID_NOT_FOUND: "ID NOT FOUND",
    ALREADY_SOLD: "ALREADY SOLD",
    OK: "OK",
    FIELD_ERROR: "FIELD ERROR",
    NO_MATCH: "NO MATCH",
    CREDENTIALS_ERROR: "CREDENTIALS ERROR"
}

module.exports = {RESPONSE_STATUS}